name: Compiler CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup dotnet
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6.0.x'

    - name: Setup clang
      uses: egor-tensin/setup-clang@v1
      with:
        version: latest

    - name: Build compiler and runtime
      run: |
        dotnet publish Compiler/Parser.fsproj -r linux-x64 -c Release -nologo -p:PublishSingleFile=true --self-contained -p:PublishReadyToRun=true
        mkdir -p target
        cp Compiler/bin/Release/net6/linux-64/publish/Parser target/chakra

    - name: Run check
      run: dotnet test Compiler/Tests/Tests.fsproj -r linux-x64 -nologo

    - name: Check executable
      run: |
        ./target/chakra > TESTING.txt
        diff TESTING.txt CMD_OUTPUT.txt
