name: Compiler CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup dotnet
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6.0.x'
    - name: Setup clang
      uses: egor-tensin/setup-clang@v1
      with:
        version: latest

    - name: configure
      run: ./configure

    - name: Install dependencies
      run: RID=linux-x64 make

    - name: Run check
      run: RID=linux-x64 make compiler_tests
